"""empty message

Revision ID: 23dd12f9ea19
Revises: 1901df823e82
Create Date: 2022-07-18 22:48:40.251195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23dd12f9ea19'
down_revision = '1901df823e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'updated')
    # ### end Alembic commands ###
