"""empty message

Revision ID: b4faf19f32bc
Revises: 23dd12f9ea19
Create Date: 2022-07-20 15:11:29.676634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4faf19f32bc'
down_revision = '23dd12f9ea19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('updated', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
